version: 0.2

phases:
  install:
    commands:
    - echo nothing to do in install phase
  pre_build:
    commands:
    - echo Nothing to do in pre_build
  build:
    commands:
    - echo Build started on `date`
    - sh gradlew build
  post_build:
    commands:
      - echo Build completed on `date`
      - sh ls -la build/libs
artifacts:
  files:
    - build/libs/springboot-helloworld.jar        
